version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 6
    default_labels:
      - "code_quality"
      - "dependencies"
    reviewers:
      - "@mozilla/fxa-devs"
